### ISSUE TITLE
npm start run failed

### ISSUE THREAD

**Issue by wanpixiaozi** [dacelee/eth-netstats#1]
~/moac-netstats$ PORT=80 WS_SECRET=moacdev.com npm start

> eth-netstats@0.0.9 start /home/moacnode/moac-netstats
> node ./bin/www

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at Object.<anonymous> (/home/moacnode/moac-netstats/app.js:411:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

below is /home/moacnode/moac-netstats/npm-debug.log
 0 info it worked if it ends with ok
1 verbose cli [ '/home/moacnode/.nvm/versions/node/v6.9.1/bin/node',
1 verbose cli   '/home/moacnode/.nvm/versions/node/v6.9.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle eth-netstats@0.0.9~prestart: eth-netstats@0.0.9
6 silly lifecycle eth-netstats@0.0.9~prestart: no script for prestart, continuing
7 info lifecycle eth-netstats@0.0.9~start: eth-netstats@0.0.9
8 verbose lifecycle eth-netstats@0.0.9~start: unsafe-perm in lifecycle true
9 verbose lifecycle eth-netstats@0.0.9~start: PATH: /home/moacnode/.nvm/versions/node/v6.9.1/lib/node_modules/npm/bin/node-gyp-bin:/home/moacnode/moac-netstats/node_modules/.bin:/home/moacnode/.nvm/versions/node/v6.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle eth-netstats@0.0.9~start: CWD: /home/moacnode/moac-netstats
11 silly lifecycle eth-netstats@0.0.9~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle eth-netstats@0.0.9~start: Returned: code: 1  signal: null
13 info lifecycle eth-netstats@0.0.9~start: Failed to exec start script
14 verbose stack Error: eth-netstats@0.0.9 start: `node ./bin/www`
14 verbose stack Exit status 1

**Comment by dacelee** [comment]
Error: listen EACCES 0.0.0.0:80
You PORT:80 is occupied.

**Comment by dacelee** [comment]
WS_SECRET=moacdev.com npm start
see the interface at http://localhost:3000
